# Dataset paths configuration for MicroVLM-E

data_root: data

datasets:
  laion:
    name: LAION-400M Subset
    type: image_text
    path: data/laion
    enabled: false
    sample_ratio: 115

  cc3m:
    name: Conceptual Captions 3M
    type: image_text
    path: data/cc3m
    enabled: false
    sample_ratio: 50

  sbu:
    name: SBU Captions
    type: image_text
    path: data/sbu
    enabled: false
    sample_ratio: 14

  coco:
    name: COCO 2017
    type: captioning
    path: data/coco
    enabled: false
    train_ann: annotations/captions_train2017.json
    val_ann: annotations/captions_val2017.json
    train_images: train2017
    val_images: val2017
    sample_ratio: 30

  vqav2:
    name: VQA v2
    type: vqa
    path: data/vqa
    enabled: false
    images: data/coco
    sample_ratio: 50

  llava_instruct:
    name: LLaVA Instruction Tuning
    type: instruction
    path: data/llava
    enabled: false
    images: data/coco
    ann_file: llava_instruct_150k.json
    sample_ratio: 100
